version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: MedFlowApp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - MedFlowApp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: MedFlowApp-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=rendez-vous-db
      - SECRET_KEY=MedFlowApp-secret-prod-change-me
    depends_on:
      - mongodb
    networks:
      - MedFlowApp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: MedFlowApp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - MedFlowApp-network

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: MedFlowApp-seed
    command: python -m app.scripts.seed
    profiles:
      - seed
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=rendez-vous-db
    depends_on:
      - mongodb
    networks:
      - MedFlowApp-network
    restart: "no"

volumes:
  mongodb_data:

networks:
  MedFlowApp-network:
    driver: bridge
