services:
  - type: web
    name: medflow-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://<USER>:<PASSWORD>@cluster0.xxxxx.mongodb.net/medflow?retryWrites=true&w=majority
      - key: SECRET_KEY
        generateValue: true
